import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from './ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from './ui/alert-dialog';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { ScrollArea } from './ui/scroll-area';
import { Separator } from './ui/separator';
import { Badge } from './ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Switch } from './ui/switch';
import { Upload, FileText, CheckCircle, AlertCircle, Trash2, RotateCcw, Globe } from 'lucide-react';
import { toast } from 'sonner@2.0.3';
import { Dictionary, SystemLanguage } from '../types/game';
import { validateDictionary, formatValidationErrors } from '../utils/dictionaryValidation';
import { getTranslation } from '../utils/translations';

interface SettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
  dictionaries: Dictionary[];
  systemLanguage: SystemLanguage;
  onToggleDictionary: (dictionaryId: string) => void;
  onAddDictionary: (dictionary: Dictionary) => void;
  onRemoveDictionary: (dictionaryId: string) => void;
  onResetProgress: () => void;
  onSetSystemLanguage: (language: SystemLanguage) => void;
}

export function SettingsModal({ 
  isOpen, 
  onClose, 
  dictionaries,
  systemLanguage,
  onToggleDictionary, 
  onAddDictionary,
  onRemoveDictionary,
  onResetProgress,
  onSetSystemLanguage
}: SettingsModalProps) {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [jsonError, setJsonError] = useState<string>('');
  const [showResetConfirm, setShowResetConfirm] = useState(false);
  const [dictionaryToDelete, setDictionaryToDelete] = useState<Dictionary | null>(null);
  
  // Get translations based on current system language
  const t = getTranslation(systemLanguage);

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      if (file.type === 'application/json' || file.name.endsWith('.json')) {
        setSelectedFile(file);
        setJsonError('');
      } else {
        setJsonError(t.toasts.invalidJson.description);
        setSelectedFile(null);
      }
    }
  };

  const handleImportDictionary = async () => {
    if (!selectedFile) return;

    try {
      const text = await selectedFile.text();
      const data = JSON.parse(text);
      
      // Use comprehensive validation function
      const validationResult = validateDictionary(data);
      
      if (!validationResult.isValid) {
        // Format and display all validation errors
        const errorMessage = formatValidationErrors(validationResult.errors);
        setJsonError(errorMessage);
        console.error('Dictionary validation failed:', validationResult.errors);
        toast.error(t.toasts.validationFailed.title, {
          description: `${validationResult.errors.length} ${t.toasts.validationFailed.description}`,
          duration: 4000,
        });
        return;
      }

      // Create dictionary object
      // Note: If progress is not provided, it will be auto-generated by the migration function
      const newDictionary: Dictionary = {
        id: `custom-${Date.now()}`,
        name: data.name,
        description: data.description || 'Custom imported dictionary',
        hanzi: data.hanzi,
        targetWords: data.targetWords,
        progress: data.progress, // Optional: will be auto-generated if missing
        isActive: true,
        isDefault: false
      };

      onAddDictionary(newDictionary);
      
      // Reset file input
      setSelectedFile(null);
      const fileInput = document.getElementById('dictionary-file') as HTMLInputElement;
      if (fileInput) fileInput.value = '';
      
      // Show success message
      toast.success(t.toasts.dictionaryImported.title, {
        description: `${data.name} ${t.toasts.dictionaryImported.description}`,
        duration: 3000,
      });
      
    } catch (error) {
      const errorMsg = 'Invalid JSON format: ' + (error as Error).message;
      setJsonError(errorMsg);
      console.error('JSON parse error:', error);
      toast.error(t.toasts.importFailed.title, {
        description: t.toasts.importFailed.description,
        duration: 3000,
      });
    }
  };

  const activeDictionaries = dictionaries.filter(d => d.isActive);
  const canToggleOff = (dictionaryId: string) => {
    return activeDictionaries.length > 1 || !activeDictionaries.some(d => d.id === dictionaryId);
  };

  const handleDeleteDictionary = (dictionary: Dictionary) => {
    setDictionaryToDelete(dictionary);
  };

  const confirmDeleteDictionary = () => {
    if (dictionaryToDelete) {
      onRemoveDictionary(dictionaryToDelete.id);
      setDictionaryToDelete(null);
    }
  };

  const handleResetProgress = () => {
    setShowResetConfirm(true);
  };

  const confirmResetProgress = () => {
    setShowResetConfirm(false);
    onResetProgress();
  };

  //old settings before manual fix <DialogContent className="max-w-[50%] h-[90vh] flex flex-col p-0 overflow-hidden">
  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl h-[90vh] max-h-[80vh] flex flex-col p-0 overflow-hidden">
        {/* Header - Fixed */}
        <div className="flex-shrink-0 p-6 pb-4">
          <DialogHeader>
            <DialogTitle className="text-center text-xl">
              {t.settings.title}
            </DialogTitle>
            <DialogDescription className="text-center">
              {t.settings.subtitle}
            </DialogDescription>
          </DialogHeader>
        </div>
        
        {/* Main Content - Scrollable */}
        <div className="flex-1 min-h-0 px-6 overflow-hidden">
          <ScrollArea className="h-full w-full pr-4">
            <div className="flex flex-col space-y-6 pb-6">
              
              {/* System Language Section */}
              <div className="flex flex-col space-y-4">
                <h3 className="flex items-center gap-2">
                  <Globe className="w-5 h-5" />
                  {t.settings.systemLanguage.title}
                </h3>
                <Card className="bg-purple-50 border-purple-200">
                  <CardHeader className="pb-3">
                    <CardDescription className="text-purple-800">
                      {t.settings.systemLanguage.description}
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="pt-0">
                    <div className="flex gap-3">
                      <Button
                        variant={systemLanguage === 'en' ? 'default' : 'outline'}
                        onClick={() => onSetSystemLanguage('en')}
                        className={systemLanguage === 'en' ? 'bg-purple-600 hover:bg-purple-700' : ''}
                      >
                        {t.settings.systemLanguage.english}
                      </Button>
                      <Button
                        variant={systemLanguage === 'pt' ? 'default' : 'outline'}
                        onClick={() => onSetSystemLanguage('pt')}
                        className={systemLanguage === 'pt' ? 'bg-purple-600 hover:bg-purple-700' : ''}
                      >
                        {t.settings.systemLanguage.portuguese}
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              </div>

              <Separator className="my-4" />
              
              {/* My Dictionaries Section */}
              <div className="flex flex-col space-y-4">
                <div className="flex items-center justify-between">
                  <h3>{t.settings.myDictionaries}</h3>
                  {activeDictionaries.length === 1 && (
                    <div className="flex items-center text-xs text-amber-600">
                      <AlertCircle className="w-3 h-3 mr-1" />
                      {t.settings.atLeastOne}
                    </div>
                  )}
                </div>
                
                {/* Dictionary Cards */}
                <div className="flex flex-col space-y-3">
                  {dictionaries.map((dictionary) => (
                    <Card key={dictionary.id} className="flex-shrink-0">
                      <CardHeader className="pb-3">
                        <div className="flex items-start justify-between gap-4">
                          <div className="flex-1 min-w-0">
                            <CardTitle className="text-base truncate">{dictionary.name}</CardTitle>
                            <CardDescription className="text-sm line-clamp-2">
                              {dictionary.description}
                            </CardDescription>
                          </div>
                          <div className="flex items-center gap-3 flex-shrink-0">
                            {dictionary.isActive && (
                              <Badge variant="default" className="bg-green-100 text-green-800 text-xs">
                                <CheckCircle className="w-3 h-3 mr-1" />
                                {t.settings.active}
                              </Badge>
                            )}
                            <div className="flex items-center space-x-2">
                              <Label htmlFor={`toggle-${dictionary.id}`} className="text-sm">
                                {dictionary.isActive ? t.settings.on : t.settings.off}
                              </Label>
                              <Switch
                                id={`toggle-${dictionary.id}`}
                                checked={dictionary.isActive}
                                onCheckedChange={() => onToggleDictionary(dictionary.id)}
                                disabled={!canToggleOff(dictionary.id)}
                              />
                            </div>
                            {!dictionary.isDefault && (
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() => handleDeleteDictionary(dictionary)}
                                className="text-red-600 hover:text-red-700 hover:bg-red-50 border-red-200"
                              >
                                <Trash2 className="w-3 h-3" />
                              </Button>
                            )}
                          </div>
                        </div>
                      </CardHeader>
                      <CardContent className="pt-0">
                        <div className="flex gap-4 text-sm text-gray-600">
                          <span>{Object.keys(dictionary.hanzi).length} {t.settings.hanzi}</span>
                          <span>•</span>
                          <span>{Object.keys(dictionary.targetWords).length} {t.settings.targetWords}</span>
                          {dictionary.isDefault && (
                            <>
                              <span>•</span>
                              <span className="text-blue-600">{t.settings.default}</span>
                            </>
                          )}
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>

                <Separator className="my-4" />

                {/* Import New Dictionary */}
                <div className="flex flex-col space-y-4">
                  <h4 className="font-medium">{t.settings.importDictionary}</h4>
                  
                  <div className="flex flex-col space-y-3">
                    <Label htmlFor="dictionary-file">{t.settings.selectFile}</Label>
                    <div className="flex items-center gap-3">
                      <Input
                        id="dictionary-file"
                        type="file"
                        accept=".json,application/json"
                        onChange={handleFileChange}
                        className="flex-1"
                      />
                      <Button
                        onClick={handleImportDictionary}
                        disabled={!selectedFile}
                        className="flex-shrink-0"
                      >
                        <Upload className="w-4 h-4 mr-2" />
                        {t.settings.import}
                      </Button>
                    </div>
                    
                    {selectedFile && (
                      <div className="flex items-center text-sm text-green-600">
                        <FileText className="w-4 h-4 mr-2" />
                        {selectedFile.name} {t.settings.selected}
                      </div>
                    )}
                    
                    {jsonError && (
                      <div className="text-sm text-red-600 whitespace-pre-line max-h-48 overflow-y-auto p-3 bg-red-50 border border-red-200 rounded">
                        {jsonError}
                      </div>
                    )}
                  </div>

                  {/* Dictionary Format Info */}
                  <Card className="bg-blue-50 border-blue-200">
                    <CardHeader className="pb-3">
                      <CardTitle className="text-sm">{t.settings.formatTitle}</CardTitle>
                    </CardHeader>
                    <CardContent className="pt-0">
                      <div className="text-xs font-mono bg-white p-3 rounded border overflow-x-auto">
                        <pre className="whitespace-pre-wrap break-all">{`{
  "id": "custom-hsk-demo",
  "name": "HSK 1 — Demo (7 Hanzi + Levels)",
  "description": "Progressive demo: hanzi unlock in 2 levels. Advance every 5 words or when all combos found.",
  "isActive": true,
  "hanzi": {
    "中": { "pinyin": "Zhōng", "en": "middle; central", "pt": "meio; central" },
    "国": { "pinyin": "guó", "en": "country; nation", "pt": "país; nação" },
    "人": { "pinyin": "rén", "en": "person", "pt": "pessoa" },
    "们": { "pinyin": "men", "en": "plural suffix", "pt": "sufixo de plural" },
    "水": { "pinyin": "shuǐ", "en": "water", "pt": "água" },
    "口": { "pinyin": "kǒu", "en": "mouth", "pt": "boca" },
    "火": { "pinyin": "huǒ", "en": "fire", "pt": "fogo" }
  },
  "targetWords": {
    "中国": { "pinyin": "Zhōngguó", "en": "China (country)", "pt": "China (país)" },
    "中国人": { "pinyin": "Zhōngguó rén", "en": "Chinese person", "pt": "pessoa chinesa" },
    "人人": { "pinyin": "rénrén", "en": "everyone", "pt": "todo mundo" },
    "人口": { "pinyin": "rénkǒu", "en": "population", "pt": "população" },
    "我们": { "pinyin": "wǒmen", "en": "we; us", "pt": "nós" },
    "你们": { "pinyin": "nǐmen", "en": "you (plural)", "pt": "vocês" },
    "口水": { "pinyin": "kǒushuǐ", "en": "saliva", "pt": "saliva" },
    "水火": { "pinyin": "shuǐhuǒ", "en": "water and fire", "pt": "água e fogo" }
  },
  "progress": {
    "advanceRule": "5_words_or_all_combos",
    "levels": [
      {
        "id": 1,
        "hanzi": ["中", "国", "人", "们"],
        "notes": "Level 1: Basic characters and nationality terms",
        "availableExamples": ["中国", "中国人", "人人", "我们", "你们"]
      },
      {
        "id": 2,
        "hanzi": ["水", "口", "火"],
        "notes": "Level 2: Elements and body parts",
        "availableExamples": ["人口", "口水", "水火"]
      }
    ]
  }
}`}</pre>
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </div>

              <Separator className="my-4" />

              {/* Game Settings Section */}
              <div className="flex flex-col space-y-4">
                <h3>{t.settings.gameSettings}</h3>
                
                <Card className="bg-red-50 border-red-200">
                  <CardHeader className="pb-3">
                    <CardTitle className="text-base text-red-800">{t.settings.resetProgress.title}</CardTitle>
                    <CardDescription className="text-red-700">
                      {t.settings.resetProgress.description}
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="pt-0">
                    <Button
                      onClick={handleResetProgress}
                      variant="destructive"
                      className="bg-red-600 hover:bg-red-700 text-white"
                    >
                      <RotateCcw className="w-4 h-4 mr-2" />
                      {t.settings.resetProgress.button}
                    </Button>
                  </CardContent>
                </Card>
              </div>

              {/* Future sections can be added here */}
              {/* Appearance Settings, etc. */}
              
            </div>
          </ScrollArea>
        </div>
      </DialogContent>

      {/* Delete Dictionary Confirmation Dialog */}
      <AlertDialog open={!!dictionaryToDelete} onOpenChange={(open) => !open && setDictionaryToDelete(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t.settings.deleteDialog.title}</AlertDialogTitle>
            <AlertDialogDescription>
              {t.settings.deleteDialog.description} "{dictionaryToDelete?.name}"?
              <br /><br />
              <strong>{t.settings.deleteDialog.warning}</strong>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{t.settings.deleteDialog.cancel}</AlertDialogCancel>
            <AlertDialogAction
              onClick={confirmDeleteDictionary}
              className="bg-red-600 hover:bg-red-700"
            >
              {t.settings.deleteDialog.delete}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Reset Progress Confirmation Dialog */}
      <AlertDialog open={showResetConfirm} onOpenChange={setShowResetConfirm}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t.settings.resetDialog.title}</AlertDialogTitle>
            <AlertDialogDescription>
              {t.settings.resetDialog.description}
              <br /><br />
              <strong>{t.settings.resetDialog.warning}</strong>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{t.settings.resetDialog.cancel}</AlertDialogCancel>
            <AlertDialogAction
              onClick={confirmResetProgress}
              className="bg-red-600 hover:bg-red-700"
            >
              {t.settings.resetDialog.reset}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </Dialog>
  );
}